[workspace]
resolver = "2"
members = [
	"crates/img-gen-spec",
	"crates/img-gen-renderer",
	"crates/img-gen",
]

[workspace.package]
edition = "2024"
authors = ["Brendan Doherty"]
license = "MIT"
repository = "https://github.com/2bndy5/img-gen"
homepage = "https://2bndy5.github.io/img-gen"

[workspace.dependencies]
fontsource_downloader = "0.3.0"
