version: "0.2"
language: en
words:
  - addopts
  - Arielle's
  - Arielles
  - armv
  - Ashville
  - asyncio
  - autoattribute
  - autoclass
  - binstall
  - bndy
  - canonicalize
  - Catmull
  - cdylib
  - Chemic
  - clippy
  - Cochiti
  - colorgrad
  - consts
  - Deque
  - Doherty
  - elif
  - endfor
  - fontconfig
  - fontdb
  - fontique
  - fontsource
  - fract
  - hustcer
  - HWBA
  - imageops
  - Inei
  - intersphinx
  - Itmeo
  - libfontconfig
  - Malinka
  - manylinux
  - maturin
  - musllinux
  - mypy
  - Nega
  - nextest
  - Palo
  - peekable
  - Pixmap
  - pkgs
  - pyclass
  - pymethods
  - pymodule
  - pypa
  - pypi
  - pytest
  - reqwest
  - resvg
  - Retrowave
  - rgba
  - Roboto
  - rustc
  - rustup
  - saphyr
  - sccache
  - sdist
  - serde
  - Sharpeye
  - skia
  - skrifa
  - staticmethod
  - struct
  - thiserror
  - toctree
  - usvg
  - venv
  - webgradients
  - zizmor
ignorePaths:
  - node_modules/**
  - target/**
  - .env/**
  - .venv/**
  - venv/**
  - env/**
  - .gitignore
  - .gitattributes
