[package]
name = "img-gen"
description = "A convenience library that re-exports public API from img-gen-spec and img-gen-renderer"
version = "0.0.0"
readme = "README.md"
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }

[lib]
name = "img_gen"
crate-type = ["cdylib", "lib"]

[dependencies]
img-gen-renderer = { path = "../img-gen-renderer" }
img-gen-spec = { path = "../img-gen-spec" }
pyo3 = { version = "0.28.3", optional = true, features = ["extension-module", "abi3-py310"] }
pyo3-async-runtimes = { version = "0.28.0", features = ["tokio-runtime"], optional = true }
tokio = { version = "1.52.3", features = ["macros"], optional = true }
reqwest = { version = "0.13", optional = true, features = ["default-tls"] }

[features]
pyo3 = [
    "dep:pyo3",
    "dep:pyo3-async-runtimes",
    "dep:tokio",
    "img-gen-spec/pyo3",
    "img-gen-renderer/pyo3",
    "dep:reqwest",
]

[dev-dependencies]
reqwest = { version = "0.13", features = ["default-tls"] }
serde-saphyr = "0.0.26"
tokio = { version = "1.52.3", features = ["macros", "rt-multi-thread"] }
