name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - run: rustup update
      - run: cargo clippy
      - run: cargo fmt --check
      - uses: actions/setup-python@v6
        id: python-setup
        with:
          python-version: 3.x
      - uses: astral-sh/setup-uv@5a7eac68fb9809dea845d802897dc5c723910fa3 # v7.1.3
        with:
          python-version: ${{ steps.python-setup.outputs.python-version }}
      - name: Cache pre-commit env
        uses: actions/cache@v4
        with:
          path: '~/.cache/pre-commit'
          key: pre-commit-${{ runner.os }}-${{ steps.python-setup.outputs.python-version }}-${{ hashFiles('.pre-commit-config.yaml') }}
      - run: uvx pre-commit run --show-diff-on-failure --color=always --all-files

  llvm-cov:
    needs: [lint]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - run: rustup update
      - run: rustup component add llvm-tools-preview
      - uses: cargo-bins/cargo-binstall@ae04fb5e853ae6cd3ad7de4a1d554a8b646d12aa # v1.15.11
      - name: Install cargo-nextest, cargo-llvm-cov, and nur
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: cargo binstall -y cargo-nextest cargo-llvm-cov nur
      - name: Run tests
        run: nur test llvm-cov
      - name: Generate coverage report
        run: nur test lcov
      - uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
        if: runner.os == 'Linux'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          fail_ci_if_error: true

  pytest:
    needs: [lint]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - run: rustup update
      - uses: actions/setup-python@v6
        id: python-setup
        with:
          python-version: 3.x
      - uses: astral-sh/setup-uv@5a7eac68fb9809dea845d802897dc5c723910fa3 # v7.1.3
        with:
          python-version: ${{ steps.python-setup.outputs.python-version }}
      - name: Run tests
        run: uv run --group test pytest
